import dynamic from 'next/dynamic'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Alert from '../components/alert'
import Posts from '../components/posts'
import { getAPI } from '../lib/callAPI'
import { getData } from '../lib/dataStore'
import PostsTypes from '../types/posts'

const Spinner = dynamic(() => import("../components/spinner"), {ssr: false})
const TextEditor = dynamic(import("../components/textEditor"), {ssr: false})

type AlertTypes = {
  show: boolean,
  status: string|null,
  statusText: string,
  type: string
}

export default function Home(): JSX.Element {
  const [posts, setposts] = useState<PostsTypes[]>([])
  const [alert, setalert] = useState<AlertTypes>({ show: false, status: null, statusText: '', type: '' })
  const [refetch, setrefetch] = useState(false)
  const [loading, setloading] = useState(true)
  const user_id = getData('user_id', 0)
  const token = getData('token', 0)
  let page = 0

  useEffect(() => {
    fetchData()
    return () => window.removeEventListener("scroll", onScroll);
  }, [])

  const onScroll = async () => {
    if ((window.innerHeight + window.scrollY) > document.body.offsetHeight) {
        window.removeEventListener("scroll", onScroll);
        setrefetch(true)
        await fetchData()
    }
  }

  const fetchData = async () => {
    const getPosts = await getAPI({ path: `posts?${user_id ? 'user_id='+user_id+'&' : ''}page=${page}` })
      
    if (getPosts.data) {
      setposts((prevState) => [...prevState, ...getPosts.data])
      if (getPosts.data.length == 10) {
        page++
        window.addEventListener("scroll", onScroll);
      }
    }
    setrefetch(false)
    setloading(false)
  }

  return (
    <>
    {
      loading ? <div className="h-100"><Spinner types='ripple' /></div> :
      <div className="container mt-5 py-5">
        <Head>
          <title>MeSo</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
          {alert.show && <Alert data={alert} />}
          {user_id && token && <TextEditor path={'posts'} />}
          <hr />
          <div className="container-fuid my-3">
            <Posts posts={posts} />
          </div>
          { refetch && <Spinner types='ring' /> }
      </div>
    }
    </>
  )
}
