import Head from 'next/head'
import { useEffect, useState } from 'react'
import Alert from '../components/alert'
import { getData } from '../lib/dataStore'

export default function Home() {
  const [posts, setposts] = useState([])
  const [alert, setalert] = useState(false)

  useEffect(() => {
    async function fetchData() {
      const user_id = await getData('user_id')
      const res = await fetch(`http://localhost:4000/api/v1/posts${user_id ? '?user_id='+user_id : ''}`, {
        method: 'GET',
        headers: {
          'Content-Type': 'application/json',
          'token': await getData('token')
        }
      })
  
      const data = await res.json()
      if (res.status === 200) {
        setposts(data.data)
        alert && setalert(false)
      }
    }
    fetchData()
  }, [])
  
  const sendPost = async(e) => {
    e.preventDefault()
    const postText = document.getElementById('postText')

    const res = await fetch(`http://localhost:4000/api/v1/posts`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'token': await getData('token')
      },
      body: JSON.stringify({
        content: postText.value,
        img_url: '',
        user_id: await getData('user_id')
      })
    })

    let data = await res.json()
    if (res.status === 200) {
      postText.value = ''
      // dipake buat comment
      // let clonePost = [...posts]
      // data.data['email'] = await getData('email')
      // clonePost.push(data.data)
      // setposts(clonePost)
      setalert(true)
      setTimeout(() => {
        setalert(false)
      }, 5000);
    }
  }

  return (
    <div className="container mt-5 py-5">
      <Head>
        <title>MeSo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        {alert && <Alert type='success' />}
        <div className="row my-3">
          <div className="col-8">
            <textarea className="form-control" placeholder="Just write" id="postText" />
          </div>
          <div className="col-4">
            <button className="form-control btn btn-success" onClick={(e) => sendPost(e)}>Send</button>
          </div>
        </div>

        <hr />
        <div className="container-fuid my-3">
          {
            posts.map(e => (
              <div className="card my-2" key={e.id}>
                <div className="card-body">
                  <strong>{e.email}</strong>
                  <p>{e.content}</p>
                </div>
            </div>
            ))
          }
        </div>
    </div>
  )
}
